spring:
  application:
    name: bookmark-services   #current service name to be used by the eureka server

# Postgres db connection
  jpa:
    database: POSTGRESQL
    hibernate:
      #ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://rajangare-learning-db.postgres.database.azure.com:5432/postgres
    username: rajangare@rajangare-learning-db
    password: raj@123.com
    driverClassName: org.postgresql.Driver
    initialization-mode: always

    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

server:
  port: 8090    #default port where the service will be started

management:
  security:
    enabled: false


eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#H2 Database config - http://localhost:8090/h2-console/login.jsp
#  datasource:
    #url: jdbc:h2:file:/data/bookmarkdb
#    url: jdbc:h2:mem:bookmarkdb
#    driverClassName: org.h2.Driver
#    username: sa
#    password:
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#  h2:
#    console:
#      enabled: true
#      path: /h2

# custom path for swagger-ui
springdoc:
  pathsToMatch: /api/**
  version: 3.0
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
  api-docs:
    path: /v3/api-docs

logging:
  level:
    org:
      springframework:
        jdbc:
          core: DEBUG