spring:
  application:
    name: bookmark-services   #current service name to be used by the eureka server

server:
  port: 8090    #default port where the service will be started

management:
  security:
    enabled: false


eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#H2 Database config - http://localhost:8090/h2-console
  datasource:
    url: jdbc:h2:file:/data/bookmarkdb
    driverClassName: org.h2.Driver
    username: admin
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2

# custom path for swagger-ui
springdoc:
  pathsToMatch: /api/**
  version: 3.0
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
  api-docs:
    path: /v3/api-docs